language: node_js

node_js:
  - 6.7.0

addons:
  apt:
    packages:
      - xvfb

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 4 # give xvfb some time to start

install:
  - npm install
